/**
 * Server-side data loader for the 5 JSON files generated by the Python ML pipeline.
 *
 * Read once at request/build time. Next.js caches these reads automatically.
 * If any file is missing, throws — the build should fail loud rather than ship blanks.
 */
import { promises as fs } from "node:fs";
import path from "node:path";

import type {
  KPIsJSON,
  ForecastsJSON,
  ModelComparisonJSON,
  InventorySignalsJSON,
  SHAPJSON,
} from "./types.generated";

const DATA_DIR = path.join(process.cwd(), "public", "data");

async function readJSON<T>(filename: string): Promise<T> {
  const filepath = path.join(DATA_DIR, filename);
  let raw: string;
  try {
    raw = await fs.readFile(filepath, "utf-8");
  } catch (err) {
    throw new Error(
      `Failed to read ${filename}. Run \`python -m ml.build_dashboard_data\` first. Original: ${
        (err as Error).message
      }`
    );
  }
  return JSON.parse(raw) as T;
}

export async function loadKPIs(): Promise<KPIsJSON> {
  return readJSON<KPIsJSON>("kpis.json");
}

export async function loadForecasts(): Promise<ForecastsJSON> {
  return readJSON<ForecastsJSON>("forecasts.json");
}

export async function loadModelComparison(): Promise<ModelComparisonJSON> {
  return readJSON<ModelComparisonJSON>("model_comparison.json");
}

export async function loadInventorySignals(): Promise<InventorySignalsJSON> {
  return readJSON<InventorySignalsJSON>("inventory_signals.json");
}

export async function loadSHAP(): Promise<SHAPJSON> {
  return readJSON<SHAPJSON>("shap.json");
}

/**
 * Worked example data — one SKU traced end-to-end through the pipeline.
 * Generated by `tools/build_worked_example.py`. Schema is intentionally
 * untyped (any) here because this is a display-only artifact rendered by
 * /methodology, not a data contract consumed by multiple pages.
 */
export interface WorkedExample {
  sku: { id: string; name: string; category: string; category_raw: string };
  train_end_date: string;
  prediction_start_date: string;
  raw_sample: {
    description: string;
    columns: string[];
    rows: (string | number | null)[][];
  };
  features: {
    description: string;
    items: { name: string; description: string; value: number }[];
  };
  prediction: {
    description: string;
    day1: { date: string; p10: number; p50: number; p90: number };
    horizon_total: { p10: number; p50: number; p90: number };
  };
  inventory_math: {
    step: number;
    label: string;
    expression: string;
    value: number;
    unit: string;
  }[];
  ledger_check: {
    description: string;
    computed_stockout_probability: number;
    stored_stockout_probability: number;
    computed_recommended_order: number;
    stored_recommended_order: number;
    computed_safety_stock: number;
    stored_safety_stock: number;
    match: boolean;
  };
}

export async function loadWorkedExample(): Promise<WorkedExample> {
  return readJSON<WorkedExample>("worked_example.json");
}

/** Load everything in parallel — useful for pages that need cross-cutting context. */
export async function loadAll() {
  const [kpis, forecasts, modelComparison, inventorySignals, shap] = await Promise.all([
    loadKPIs(),
    loadForecasts(),
    loadModelComparison(),
    loadInventorySignals(),
    loadSHAP(),
  ]);
  return { kpis, forecasts, modelComparison, inventorySignals, shap };
}

export type {
  KPIsJSON,
  ForecastsJSON,
  ModelComparisonJSON,
  InventorySignalsJSON,
  SHAPJSON,
} from "./types.generated";
