/**
 * Server-side data loader for the 5 JSON files generated by the Python ML pipeline.
 *
 * Read once at request/build time. Next.js caches these reads automatically.
 * If any file is missing, throws — the build should fail loud rather than ship blanks.
 */
import { promises as fs } from "node:fs";
import path from "node:path";

import type {
  KPIsJSON,
  ForecastsJSON,
  ModelComparisonJSON,
  InventorySignalsJSON,
  SHAPJSON,
} from "./types.generated";

const DATA_DIR = path.join(process.cwd(), "public", "data");

async function readJSON<T>(filename: string): Promise<T> {
  const filepath = path.join(DATA_DIR, filename);
  let raw: string;
  try {
    raw = await fs.readFile(filepath, "utf-8");
  } catch (err) {
    throw new Error(
      `Failed to read ${filename}. Run \`python -m ml.build_dashboard_data\` first. Original: ${
        (err as Error).message
      }`
    );
  }
  return JSON.parse(raw) as T;
}

export async function loadKPIs(): Promise<KPIsJSON> {
  return readJSON<KPIsJSON>("kpis.json");
}

export async function loadForecasts(): Promise<ForecastsJSON> {
  return readJSON<ForecastsJSON>("forecasts.json");
}

export async function loadModelComparison(): Promise<ModelComparisonJSON> {
  return readJSON<ModelComparisonJSON>("model_comparison.json");
}

export async function loadInventorySignals(): Promise<InventorySignalsJSON> {
  return readJSON<InventorySignalsJSON>("inventory_signals.json");
}

export async function loadSHAP(): Promise<SHAPJSON> {
  return readJSON<SHAPJSON>("shap.json");
}

/** Load everything in parallel — useful for pages that need cross-cutting context. */
export async function loadAll() {
  const [kpis, forecasts, modelComparison, inventorySignals, shap] = await Promise.all([
    loadKPIs(),
    loadForecasts(),
    loadModelComparison(),
    loadInventorySignals(),
    loadSHAP(),
  ]);
  return { kpis, forecasts, modelComparison, inventorySignals, shap };
}

export type {
  KPIsJSON,
  ForecastsJSON,
  ModelComparisonJSON,
  InventorySignalsJSON,
  SHAPJSON,
} from "./types.generated";
